/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jlb.devcloud

import aws.sdk.kotlin.services.s3.S3Client
import kotlinx.coroutines.runBlocking
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class DevcloudPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.apple.xcard.devcloud.greeting'")
            }
        }

        project.tasks.register("buckets") { task ->
            task.doLast {
                runBlocking {
                    val s3 = S3Client { region = "us-west-2" }
                    val response = s3.listBuckets { }
                    response.buckets?.forEach { println(it.name) }
                }
            }
        }
    }
}
